# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 02:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('bio', models.TextField(max_length=3000)),
                ('headshot', models.ImageField(blank=True, upload_to='artist_headshots')),
                ('banner', models.ImageField(blank=True, upload_to='artist_banners')),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
            ],
        ),
    ]
