# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 04:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='banner',
            field=models.ImageField(blank=True, upload_to='artist-banners'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='headshot',
            field=models.ImageField(blank=True, upload_to='artist-headshots'),
        ),
    ]
